### ISSUE TITLE
Support UEFA EURO 2021

### ISSUE THREAD

**Issue by siloor** [lsv/uefa-euro-2020#2]
Hello @lsv !

At first, thank you for your great football databases! I used your fifa-world-cup-2018 json by a small company website and it was a huge help!

Do you plan to maintain the json for the delayed championship starting at Jun 11, 2021?

**Comment by lalamm** [comment]
+1 from me. It was super useful!

**Comment by lsv** [comment]
Is has now been updated to 2021 dates, teams and stadium has been updated
